CREATE TABLE TABLE_NAME (
    ID SERIAL PRIMARY KEY,
    CONTENT TEXT
);

SELECT
    EXISTS (
        SELECT
        FROM
            INFORMATION_SCHEMA.TABLES
        WHERE
            TABLE_NAME = 'TABLE_NAME'
            AND TABLE_SCHEMA = 'public'
    );